// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: verrpc/verrpc.proto

package verrpc;

public final class Verrpc {
  private Verrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VersionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:verrpc.VersionRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code verrpc.VersionRequest}
   */
  public  static final class VersionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:verrpc.VersionRequest)
      VersionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VersionRequest.newBuilder() to construct.
    private VersionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VersionRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VersionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return verrpc.Verrpc.internal_static_verrpc_VersionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return verrpc.Verrpc.internal_static_verrpc_VersionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              verrpc.Verrpc.VersionRequest.class, verrpc.Verrpc.VersionRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof verrpc.Verrpc.VersionRequest)) {
        return super.equals(obj);
      }
      verrpc.Verrpc.VersionRequest other = (verrpc.Verrpc.VersionRequest) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static verrpc.Verrpc.VersionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static verrpc.Verrpc.VersionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static verrpc.Verrpc.VersionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static verrpc.Verrpc.VersionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static verrpc.Verrpc.VersionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static verrpc.Verrpc.VersionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static verrpc.Verrpc.VersionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static verrpc.Verrpc.VersionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static verrpc.Verrpc.VersionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static verrpc.Verrpc.VersionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static verrpc.Verrpc.VersionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static verrpc.Verrpc.VersionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(verrpc.Verrpc.VersionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code verrpc.VersionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:verrpc.VersionRequest)
        verrpc.Verrpc.VersionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return verrpc.Verrpc.internal_static_verrpc_VersionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return verrpc.Verrpc.internal_static_verrpc_VersionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                verrpc.Verrpc.VersionRequest.class, verrpc.Verrpc.VersionRequest.Builder.class);
      }

      // Construct using verrpc.Verrpc.VersionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return verrpc.Verrpc.internal_static_verrpc_VersionRequest_descriptor;
      }

      @java.lang.Override
      public verrpc.Verrpc.VersionRequest getDefaultInstanceForType() {
        return verrpc.Verrpc.VersionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public verrpc.Verrpc.VersionRequest build() {
        verrpc.Verrpc.VersionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public verrpc.Verrpc.VersionRequest buildPartial() {
        verrpc.Verrpc.VersionRequest result = new verrpc.Verrpc.VersionRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof verrpc.Verrpc.VersionRequest) {
          return mergeFrom((verrpc.Verrpc.VersionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(verrpc.Verrpc.VersionRequest other) {
        if (other == verrpc.Verrpc.VersionRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        verrpc.Verrpc.VersionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (verrpc.Verrpc.VersionRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:verrpc.VersionRequest)
    }

    // @@protoc_insertion_point(class_scope:verrpc.VersionRequest)
    private static final verrpc.Verrpc.VersionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new verrpc.Verrpc.VersionRequest();
    }

    public static verrpc.Verrpc.VersionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VersionRequest>
        PARSER = new com.google.protobuf.AbstractParser<VersionRequest>() {
      @java.lang.Override
      public VersionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VersionRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VersionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VersionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public verrpc.Verrpc.VersionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VersionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:verrpc.Version)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * A verbose description of the daemon's commit.
     * </pre>
     *
     * <code>string commit = 1;</code>
     */
    java.lang.String getCommit();
    /**
     * <pre>
     * A verbose description of the daemon's commit.
     * </pre>
     *
     * <code>string commit = 1;</code>
     */
    com.google.protobuf.ByteString
        getCommitBytes();

    /**
     * <pre>
     * The SHA1 commit hash that the daemon is compiled with.
     * </pre>
     *
     * <code>string commit_hash = 2;</code>
     */
    java.lang.String getCommitHash();
    /**
     * <pre>
     * The SHA1 commit hash that the daemon is compiled with.
     * </pre>
     *
     * <code>string commit_hash = 2;</code>
     */
    com.google.protobuf.ByteString
        getCommitHashBytes();

    /**
     * <pre>
     * The semantic version.
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    java.lang.String getVersion();
    /**
     * <pre>
     * The semantic version.
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <pre>
     * The major application version.
     * </pre>
     *
     * <code>uint32 app_major = 4;</code>
     */
    int getAppMajor();

    /**
     * <pre>
     * The minor application version.
     * </pre>
     *
     * <code>uint32 app_minor = 5;</code>
     */
    int getAppMinor();

    /**
     * <pre>
     * The application patch number.
     * </pre>
     *
     * <code>uint32 app_patch = 6;</code>
     */
    int getAppPatch();

    /**
     * <pre>
     * The application pre-release modifier, possibly empty.
     * </pre>
     *
     * <code>string app_pre_release = 7;</code>
     */
    java.lang.String getAppPreRelease();
    /**
     * <pre>
     * The application pre-release modifier, possibly empty.
     * </pre>
     *
     * <code>string app_pre_release = 7;</code>
     */
    com.google.protobuf.ByteString
        getAppPreReleaseBytes();

    /**
     * <pre>
     * The list of build tags that were supplied during compilation.
     * </pre>
     *
     * <code>repeated string build_tags = 8;</code>
     */
    java.util.List<java.lang.String>
        getBuildTagsList();
    /**
     * <pre>
     * The list of build tags that were supplied during compilation.
     * </pre>
     *
     * <code>repeated string build_tags = 8;</code>
     */
    int getBuildTagsCount();
    /**
     * <pre>
     * The list of build tags that were supplied during compilation.
     * </pre>
     *
     * <code>repeated string build_tags = 8;</code>
     */
    java.lang.String getBuildTags(int index);
    /**
     * <pre>
     * The list of build tags that were supplied during compilation.
     * </pre>
     *
     * <code>repeated string build_tags = 8;</code>
     */
    com.google.protobuf.ByteString
        getBuildTagsBytes(int index);

    /**
     * <pre>
     * The version of go that compiled the executable.
     * </pre>
     *
     * <code>string go_version = 9;</code>
     */
    java.lang.String getGoVersion();
    /**
     * <pre>
     * The version of go that compiled the executable.
     * </pre>
     *
     * <code>string go_version = 9;</code>
     */
    com.google.protobuf.ByteString
        getGoVersionBytes();
  }
  /**
   * Protobuf type {@code verrpc.Version}
   */
  public  static final class Version extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:verrpc.Version)
      VersionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Version.newBuilder() to construct.
    private Version(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Version() {
      commit_ = "";
      commitHash_ = "";
      version_ = "";
      appMajor_ = 0;
      appMinor_ = 0;
      appPatch_ = 0;
      appPreRelease_ = "";
      buildTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      goVersion_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Version(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              commit_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              commitHash_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 32: {

              appMajor_ = input.readUInt32();
              break;
            }
            case 40: {

              appMinor_ = input.readUInt32();
              break;
            }
            case 48: {

              appPatch_ = input.readUInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              appPreRelease_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                buildTags_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000080;
              }
              buildTags_.add(s);
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              goVersion_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          buildTags_ = buildTags_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return verrpc.Verrpc.internal_static_verrpc_Version_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return verrpc.Verrpc.internal_static_verrpc_Version_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              verrpc.Verrpc.Version.class, verrpc.Verrpc.Version.Builder.class);
    }

    private int bitField0_;
    public static final int COMMIT_FIELD_NUMBER = 1;
    private volatile java.lang.Object commit_;
    /**
     * <pre>
     * A verbose description of the daemon's commit.
     * </pre>
     *
     * <code>string commit = 1;</code>
     */
    public java.lang.String getCommit() {
      java.lang.Object ref = commit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commit_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * A verbose description of the daemon's commit.
     * </pre>
     *
     * <code>string commit = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCommitBytes() {
      java.lang.Object ref = commit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMIT_HASH_FIELD_NUMBER = 2;
    private volatile java.lang.Object commitHash_;
    /**
     * <pre>
     * The SHA1 commit hash that the daemon is compiled with.
     * </pre>
     *
     * <code>string commit_hash = 2;</code>
     */
    public java.lang.String getCommitHash() {
      java.lang.Object ref = commitHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commitHash_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The SHA1 commit hash that the daemon is compiled with.
     * </pre>
     *
     * <code>string commit_hash = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCommitHashBytes() {
      java.lang.Object ref = commitHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commitHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private volatile java.lang.Object version_;
    /**
     * <pre>
     * The semantic version.
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The semantic version.
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_MAJOR_FIELD_NUMBER = 4;
    private int appMajor_;
    /**
     * <pre>
     * The major application version.
     * </pre>
     *
     * <code>uint32 app_major = 4;</code>
     */
    public int getAppMajor() {
      return appMajor_;
    }

    public static final int APP_MINOR_FIELD_NUMBER = 5;
    private int appMinor_;
    /**
     * <pre>
     * The minor application version.
     * </pre>
     *
     * <code>uint32 app_minor = 5;</code>
     */
    public int getAppMinor() {
      return appMinor_;
    }

    public static final int APP_PATCH_FIELD_NUMBER = 6;
    private int appPatch_;
    /**
     * <pre>
     * The application patch number.
     * </pre>
     *
     * <code>uint32 app_patch = 6;</code>
     */
    public int getAppPatch() {
      return appPatch_;
    }

    public static final int APP_PRE_RELEASE_FIELD_NUMBER = 7;
    private volatile java.lang.Object appPreRelease_;
    /**
     * <pre>
     * The application pre-release modifier, possibly empty.
     * </pre>
     *
     * <code>string app_pre_release = 7;</code>
     */
    public java.lang.String getAppPreRelease() {
      java.lang.Object ref = appPreRelease_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appPreRelease_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The application pre-release modifier, possibly empty.
     * </pre>
     *
     * <code>string app_pre_release = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAppPreReleaseBytes() {
      java.lang.Object ref = appPreRelease_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appPreRelease_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUILD_TAGS_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList buildTags_;
    /**
     * <pre>
     * The list of build tags that were supplied during compilation.
     * </pre>
     *
     * <code>repeated string build_tags = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getBuildTagsList() {
      return buildTags_;
    }
    /**
     * <pre>
     * The list of build tags that were supplied during compilation.
     * </pre>
     *
     * <code>repeated string build_tags = 8;</code>
     */
    public int getBuildTagsCount() {
      return buildTags_.size();
    }
    /**
     * <pre>
     * The list of build tags that were supplied during compilation.
     * </pre>
     *
     * <code>repeated string build_tags = 8;</code>
     */
    public java.lang.String getBuildTags(int index) {
      return buildTags_.get(index);
    }
    /**
     * <pre>
     * The list of build tags that were supplied during compilation.
     * </pre>
     *
     * <code>repeated string build_tags = 8;</code>
     */
    public com.google.protobuf.ByteString
        getBuildTagsBytes(int index) {
      return buildTags_.getByteString(index);
    }

    public static final int GO_VERSION_FIELD_NUMBER = 9;
    private volatile java.lang.Object goVersion_;
    /**
     * <pre>
     * The version of go that compiled the executable.
     * </pre>
     *
     * <code>string go_version = 9;</code>
     */
    public java.lang.String getGoVersion() {
      java.lang.Object ref = goVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        goVersion_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The version of go that compiled the executable.
     * </pre>
     *
     * <code>string go_version = 9;</code>
     */
    public com.google.protobuf.ByteString
        getGoVersionBytes() {
      java.lang.Object ref = goVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        goVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCommitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, commit_);
      }
      if (!getCommitHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, commitHash_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, version_);
      }
      if (appMajor_ != 0) {
        output.writeUInt32(4, appMajor_);
      }
      if (appMinor_ != 0) {
        output.writeUInt32(5, appMinor_);
      }
      if (appPatch_ != 0) {
        output.writeUInt32(6, appPatch_);
      }
      if (!getAppPreReleaseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, appPreRelease_);
      }
      for (int i = 0; i < buildTags_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, buildTags_.getRaw(i));
      }
      if (!getGoVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, goVersion_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCommitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, commit_);
      }
      if (!getCommitHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, commitHash_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, version_);
      }
      if (appMajor_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, appMajor_);
      }
      if (appMinor_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, appMinor_);
      }
      if (appPatch_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, appPatch_);
      }
      if (!getAppPreReleaseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, appPreRelease_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < buildTags_.size(); i++) {
          dataSize += computeStringSizeNoTag(buildTags_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getBuildTagsList().size();
      }
      if (!getGoVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, goVersion_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof verrpc.Verrpc.Version)) {
        return super.equals(obj);
      }
      verrpc.Verrpc.Version other = (verrpc.Verrpc.Version) obj;

      boolean result = true;
      result = result && getCommit()
          .equals(other.getCommit());
      result = result && getCommitHash()
          .equals(other.getCommitHash());
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && (getAppMajor()
          == other.getAppMajor());
      result = result && (getAppMinor()
          == other.getAppMinor());
      result = result && (getAppPatch()
          == other.getAppPatch());
      result = result && getAppPreRelease()
          .equals(other.getAppPreRelease());
      result = result && getBuildTagsList()
          .equals(other.getBuildTagsList());
      result = result && getGoVersion()
          .equals(other.getGoVersion());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMIT_FIELD_NUMBER;
      hash = (53 * hash) + getCommit().hashCode();
      hash = (37 * hash) + COMMIT_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getCommitHash().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + APP_MAJOR_FIELD_NUMBER;
      hash = (53 * hash) + getAppMajor();
      hash = (37 * hash) + APP_MINOR_FIELD_NUMBER;
      hash = (53 * hash) + getAppMinor();
      hash = (37 * hash) + APP_PATCH_FIELD_NUMBER;
      hash = (53 * hash) + getAppPatch();
      hash = (37 * hash) + APP_PRE_RELEASE_FIELD_NUMBER;
      hash = (53 * hash) + getAppPreRelease().hashCode();
      if (getBuildTagsCount() > 0) {
        hash = (37 * hash) + BUILD_TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getBuildTagsList().hashCode();
      }
      hash = (37 * hash) + GO_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getGoVersion().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static verrpc.Verrpc.Version parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static verrpc.Verrpc.Version parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static verrpc.Verrpc.Version parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static verrpc.Verrpc.Version parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static verrpc.Verrpc.Version parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static verrpc.Verrpc.Version parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static verrpc.Verrpc.Version parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static verrpc.Verrpc.Version parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static verrpc.Verrpc.Version parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static verrpc.Verrpc.Version parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static verrpc.Verrpc.Version parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static verrpc.Verrpc.Version parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(verrpc.Verrpc.Version prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code verrpc.Version}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:verrpc.Version)
        verrpc.Verrpc.VersionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return verrpc.Verrpc.internal_static_verrpc_Version_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return verrpc.Verrpc.internal_static_verrpc_Version_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                verrpc.Verrpc.Version.class, verrpc.Verrpc.Version.Builder.class);
      }

      // Construct using verrpc.Verrpc.Version.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        commit_ = "";

        commitHash_ = "";

        version_ = "";

        appMajor_ = 0;

        appMinor_ = 0;

        appPatch_ = 0;

        appPreRelease_ = "";

        buildTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        goVersion_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return verrpc.Verrpc.internal_static_verrpc_Version_descriptor;
      }

      @java.lang.Override
      public verrpc.Verrpc.Version getDefaultInstanceForType() {
        return verrpc.Verrpc.Version.getDefaultInstance();
      }

      @java.lang.Override
      public verrpc.Verrpc.Version build() {
        verrpc.Verrpc.Version result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public verrpc.Verrpc.Version buildPartial() {
        verrpc.Verrpc.Version result = new verrpc.Verrpc.Version(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.commit_ = commit_;
        result.commitHash_ = commitHash_;
        result.version_ = version_;
        result.appMajor_ = appMajor_;
        result.appMinor_ = appMinor_;
        result.appPatch_ = appPatch_;
        result.appPreRelease_ = appPreRelease_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          buildTags_ = buildTags_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.buildTags_ = buildTags_;
        result.goVersion_ = goVersion_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof verrpc.Verrpc.Version) {
          return mergeFrom((verrpc.Verrpc.Version)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(verrpc.Verrpc.Version other) {
        if (other == verrpc.Verrpc.Version.getDefaultInstance()) return this;
        if (!other.getCommit().isEmpty()) {
          commit_ = other.commit_;
          onChanged();
        }
        if (!other.getCommitHash().isEmpty()) {
          commitHash_ = other.commitHash_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.getAppMajor() != 0) {
          setAppMajor(other.getAppMajor());
        }
        if (other.getAppMinor() != 0) {
          setAppMinor(other.getAppMinor());
        }
        if (other.getAppPatch() != 0) {
          setAppPatch(other.getAppPatch());
        }
        if (!other.getAppPreRelease().isEmpty()) {
          appPreRelease_ = other.appPreRelease_;
          onChanged();
        }
        if (!other.buildTags_.isEmpty()) {
          if (buildTags_.isEmpty()) {
            buildTags_ = other.buildTags_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureBuildTagsIsMutable();
            buildTags_.addAll(other.buildTags_);
          }
          onChanged();
        }
        if (!other.getGoVersion().isEmpty()) {
          goVersion_ = other.goVersion_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        verrpc.Verrpc.Version parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (verrpc.Verrpc.Version) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object commit_ = "";
      /**
       * <pre>
       * A verbose description of the daemon's commit.
       * </pre>
       *
       * <code>string commit = 1;</code>
       */
      public java.lang.String getCommit() {
        java.lang.Object ref = commit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          commit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * A verbose description of the daemon's commit.
       * </pre>
       *
       * <code>string commit = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCommitBytes() {
        java.lang.Object ref = commit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * A verbose description of the daemon's commit.
       * </pre>
       *
       * <code>string commit = 1;</code>
       */
      public Builder setCommit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        commit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A verbose description of the daemon's commit.
       * </pre>
       *
       * <code>string commit = 1;</code>
       */
      public Builder clearCommit() {
        
        commit_ = getDefaultInstance().getCommit();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A verbose description of the daemon's commit.
       * </pre>
       *
       * <code>string commit = 1;</code>
       */
      public Builder setCommitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        commit_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object commitHash_ = "";
      /**
       * <pre>
       * The SHA1 commit hash that the daemon is compiled with.
       * </pre>
       *
       * <code>string commit_hash = 2;</code>
       */
      public java.lang.String getCommitHash() {
        java.lang.Object ref = commitHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          commitHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The SHA1 commit hash that the daemon is compiled with.
       * </pre>
       *
       * <code>string commit_hash = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCommitHashBytes() {
        java.lang.Object ref = commitHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commitHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The SHA1 commit hash that the daemon is compiled with.
       * </pre>
       *
       * <code>string commit_hash = 2;</code>
       */
      public Builder setCommitHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        commitHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The SHA1 commit hash that the daemon is compiled with.
       * </pre>
       *
       * <code>string commit_hash = 2;</code>
       */
      public Builder clearCommitHash() {
        
        commitHash_ = getDefaultInstance().getCommitHash();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The SHA1 commit hash that the daemon is compiled with.
       * </pre>
       *
       * <code>string commit_hash = 2;</code>
       */
      public Builder setCommitHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        commitHash_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <pre>
       * The semantic version.
       * </pre>
       *
       * <code>string version = 3;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The semantic version.
       * </pre>
       *
       * <code>string version = 3;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The semantic version.
       * </pre>
       *
       * <code>string version = 3;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The semantic version.
       * </pre>
       *
       * <code>string version = 3;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The semantic version.
       * </pre>
       *
       * <code>string version = 3;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private int appMajor_ ;
      /**
       * <pre>
       * The major application version.
       * </pre>
       *
       * <code>uint32 app_major = 4;</code>
       */
      public int getAppMajor() {
        return appMajor_;
      }
      /**
       * <pre>
       * The major application version.
       * </pre>
       *
       * <code>uint32 app_major = 4;</code>
       */
      public Builder setAppMajor(int value) {
        
        appMajor_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The major application version.
       * </pre>
       *
       * <code>uint32 app_major = 4;</code>
       */
      public Builder clearAppMajor() {
        
        appMajor_ = 0;
        onChanged();
        return this;
      }

      private int appMinor_ ;
      /**
       * <pre>
       * The minor application version.
       * </pre>
       *
       * <code>uint32 app_minor = 5;</code>
       */
      public int getAppMinor() {
        return appMinor_;
      }
      /**
       * <pre>
       * The minor application version.
       * </pre>
       *
       * <code>uint32 app_minor = 5;</code>
       */
      public Builder setAppMinor(int value) {
        
        appMinor_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The minor application version.
       * </pre>
       *
       * <code>uint32 app_minor = 5;</code>
       */
      public Builder clearAppMinor() {
        
        appMinor_ = 0;
        onChanged();
        return this;
      }

      private int appPatch_ ;
      /**
       * <pre>
       * The application patch number.
       * </pre>
       *
       * <code>uint32 app_patch = 6;</code>
       */
      public int getAppPatch() {
        return appPatch_;
      }
      /**
       * <pre>
       * The application patch number.
       * </pre>
       *
       * <code>uint32 app_patch = 6;</code>
       */
      public Builder setAppPatch(int value) {
        
        appPatch_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The application patch number.
       * </pre>
       *
       * <code>uint32 app_patch = 6;</code>
       */
      public Builder clearAppPatch() {
        
        appPatch_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object appPreRelease_ = "";
      /**
       * <pre>
       * The application pre-release modifier, possibly empty.
       * </pre>
       *
       * <code>string app_pre_release = 7;</code>
       */
      public java.lang.String getAppPreRelease() {
        java.lang.Object ref = appPreRelease_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appPreRelease_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The application pre-release modifier, possibly empty.
       * </pre>
       *
       * <code>string app_pre_release = 7;</code>
       */
      public com.google.protobuf.ByteString
          getAppPreReleaseBytes() {
        java.lang.Object ref = appPreRelease_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appPreRelease_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The application pre-release modifier, possibly empty.
       * </pre>
       *
       * <code>string app_pre_release = 7;</code>
       */
      public Builder setAppPreRelease(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appPreRelease_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The application pre-release modifier, possibly empty.
       * </pre>
       *
       * <code>string app_pre_release = 7;</code>
       */
      public Builder clearAppPreRelease() {
        
        appPreRelease_ = getDefaultInstance().getAppPreRelease();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The application pre-release modifier, possibly empty.
       * </pre>
       *
       * <code>string app_pre_release = 7;</code>
       */
      public Builder setAppPreReleaseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appPreRelease_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList buildTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBuildTagsIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          buildTags_ = new com.google.protobuf.LazyStringArrayList(buildTags_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <pre>
       * The list of build tags that were supplied during compilation.
       * </pre>
       *
       * <code>repeated string build_tags = 8;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getBuildTagsList() {
        return buildTags_.getUnmodifiableView();
      }
      /**
       * <pre>
       * The list of build tags that were supplied during compilation.
       * </pre>
       *
       * <code>repeated string build_tags = 8;</code>
       */
      public int getBuildTagsCount() {
        return buildTags_.size();
      }
      /**
       * <pre>
       * The list of build tags that were supplied during compilation.
       * </pre>
       *
       * <code>repeated string build_tags = 8;</code>
       */
      public java.lang.String getBuildTags(int index) {
        return buildTags_.get(index);
      }
      /**
       * <pre>
       * The list of build tags that were supplied during compilation.
       * </pre>
       *
       * <code>repeated string build_tags = 8;</code>
       */
      public com.google.protobuf.ByteString
          getBuildTagsBytes(int index) {
        return buildTags_.getByteString(index);
      }
      /**
       * <pre>
       * The list of build tags that were supplied during compilation.
       * </pre>
       *
       * <code>repeated string build_tags = 8;</code>
       */
      public Builder setBuildTags(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBuildTagsIsMutable();
        buildTags_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The list of build tags that were supplied during compilation.
       * </pre>
       *
       * <code>repeated string build_tags = 8;</code>
       */
      public Builder addBuildTags(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBuildTagsIsMutable();
        buildTags_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The list of build tags that were supplied during compilation.
       * </pre>
       *
       * <code>repeated string build_tags = 8;</code>
       */
      public Builder addAllBuildTags(
          java.lang.Iterable<java.lang.String> values) {
        ensureBuildTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, buildTags_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The list of build tags that were supplied during compilation.
       * </pre>
       *
       * <code>repeated string build_tags = 8;</code>
       */
      public Builder clearBuildTags() {
        buildTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The list of build tags that were supplied during compilation.
       * </pre>
       *
       * <code>repeated string build_tags = 8;</code>
       */
      public Builder addBuildTagsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureBuildTagsIsMutable();
        buildTags_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object goVersion_ = "";
      /**
       * <pre>
       * The version of go that compiled the executable.
       * </pre>
       *
       * <code>string go_version = 9;</code>
       */
      public java.lang.String getGoVersion() {
        java.lang.Object ref = goVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          goVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The version of go that compiled the executable.
       * </pre>
       *
       * <code>string go_version = 9;</code>
       */
      public com.google.protobuf.ByteString
          getGoVersionBytes() {
        java.lang.Object ref = goVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          goVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The version of go that compiled the executable.
       * </pre>
       *
       * <code>string go_version = 9;</code>
       */
      public Builder setGoVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        goVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The version of go that compiled the executable.
       * </pre>
       *
       * <code>string go_version = 9;</code>
       */
      public Builder clearGoVersion() {
        
        goVersion_ = getDefaultInstance().getGoVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The version of go that compiled the executable.
       * </pre>
       *
       * <code>string go_version = 9;</code>
       */
      public Builder setGoVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        goVersion_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:verrpc.Version)
    }

    // @@protoc_insertion_point(class_scope:verrpc.Version)
    private static final verrpc.Verrpc.Version DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new verrpc.Verrpc.Version();
    }

    public static verrpc.Verrpc.Version getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Version>
        PARSER = new com.google.protobuf.AbstractParser<Version>() {
      @java.lang.Override
      public Version parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Version(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Version> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Version> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public verrpc.Verrpc.Version getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_verrpc_VersionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_verrpc_VersionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_verrpc_Version_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_verrpc_Version_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023verrpc/verrpc.proto\022\006verrpc\"\020\n\016Version" +
      "Request\"\271\001\n\007Version\022\016\n\006commit\030\001 \001(\t\022\023\n\013c" +
      "ommit_hash\030\002 \001(\t\022\017\n\007version\030\003 \001(\t\022\021\n\tapp" +
      "_major\030\004 \001(\r\022\021\n\tapp_minor\030\005 \001(\r\022\021\n\tapp_p" +
      "atch\030\006 \001(\r\022\027\n\017app_pre_release\030\007 \001(\t\022\022\n\nb" +
      "uild_tags\030\010 \003(\t\022\022\n\ngo_version\030\t \001(\t2B\n\tV" +
      "ersioner\0225\n\nGetVersion\022\026.verrpc.VersionR" +
      "equest\032\017.verrpc.VersionB.Z,github.com/li" +
      "ghtningnetwork/lnd/lnrpc/verrpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_verrpc_VersionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_verrpc_VersionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_verrpc_VersionRequest_descriptor,
        new java.lang.String[] { });
    internal_static_verrpc_Version_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_verrpc_Version_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_verrpc_Version_descriptor,
        new java.lang.String[] { "Commit", "CommitHash", "Version", "AppMajor", "AppMinor", "AppPatch", "AppPreRelease", "BuildTags", "GoVersion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
